// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wxqyubcuocnwpvsaylle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4cXl1YmN1b2Nud3B2c2F5bGxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MzgyODYsImV4cCI6MjA2OTMxNDI4Nn0.hvoSdGxGqrM_SpcQ87VVCawbuvAfOWhZewrbrCmeN58";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);